server:
  port: 8082

spring:
  datasource:
   url: jdbc:postgresql://114.132.51.227:5432/ooad_proj
   username: ooad_admin
   password: '111111'

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ooad.dormitory: debug